before_install: gem install bundler --pre
before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email:
    - kennyadsl@gmail.com
    - mtylty@gmail.com
branches:
  only:
    - master
    - 2-1-stable
    - 2-0-stable
    - 1-3-stable
    - 1-2-stable
    - 1-1-stable
    - 1-0-stable
rvm:
  - 1.9.3
