source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'pg'

gem 'sass-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'compass-rails'
gem 'font-awesome-rails'
gem 'uglifier', '>= 1.3.0'
gem 'therubyracer', platforms: :ruby
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'
gem 'activeadmin', '~> 1.0.0.pre5'
gem 'devise', '~> 3.2'
gem 'draper', '~> 1.3'
gem 'omniauth', '~> 1.2.2'
gem 'ruby_rncryptor', '~> 3.0.0'
#gem 'appsignal', '~> 0.12.rc'
gem 'paperclip', "~> 4.3"
gem 'httparty'
gem 'stripe', :git => 'https://github.com/stripe/stripe-ruby'
gem 'mapbox-rails', :git => 'https://github.com/dkniffin/mapbox-rails'
gem 'animate-rails'
gem 'mail'
gem 'lz4-ruby'
gem 'country_select'
gem 'nokogiri', '~> 1.6.7.2'
gem 'parallel'
gem 'ruby-progressbar'
gem 'createsend'
gem 'gon'

gem 'spree', '~> 3.1.0'
gem 'spree_auth_devise', '~> 3.1.0'
gem 'spree_gateway', '~> 3.1.0'

gem 'spree_simple_delivery', path: '../spree_simple_delivery'
gem 'spree_prescription', path: '../spree_prescription'
gem 'spree_preorder', path: '../spree_preorder'
gem 'spree_garbage_cleaner', path: '../spree-garbage-cleaner'
gem 'spree_createsend', path: '../spree_createsend'
gem 'spree_dynamic_variants', path: '../spree_dynamic_variants'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
end
